services:
  - type: web
    name: telegram-bot
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node bot.js'
    autoDeploy: true
    envVars:
      - key: TELEGRAM_TOKEN
        fromDotEnv: true
